### ISSUE TITLE
Valid german IBAN is not considered valid

### ISSUE THREAD

**Issue by s-gurevich** [baumerdev/ibantools-germany#14]
## Expected Behavior
A specific valid IBAN is recognized as valid by `isValidIBAN` function.

## Actual Behavior
A specific valid IBAN is NOT recognized as valid by `isValidIBAN` function.

## Steps to Reproduce the Problem

Given:
`import { isValidIBAN } from 'ibantools-germany';`

1. `isValidIBAN(electronicIban)` usually qualifies German IBANs correctly
2. A single specific IBAN is not recognized as valid, while https://www.iban-rechner.de/iban_validieren.html states, that it is valid
3. I cannot share the IBAN, because it's personal data, but maybe this helps:

BIC: DAAEDEDDXXX (Düsseldorf)   

Bank: apoBank

DEUTSCHE APOTHEKER- UND ÄRZTEBANK
Richard-Oskar-Mattern-Straße 6
40547 Düsseldorf

## Specifications

Tested with
"ibantools-germany": "1.2301.2" and "1.2301.3",

**Comment by baumerdev** [comment]
@s-gurevich Just to be sure, since this library works with BLZ, we're talking about 30060601 (characters 5-12 of IBAN)?

The method for this BLZ would be A4 which consists of multiple different calculation methods, usually due to legacy methods, bank mergers etc. All tests for the different variations with all the test numbers provided by Bundesbank return the expected results and I wasn't able to spot something something that seems to be implemented wrongly (which doesn't mean that there isn't an error). It may as well be an ambiguous definition the official document (which sadly wouldn't be a first neither). 

Let's try to narrow it down somehow.

Can you use the function `isValidAccountNumberBLZ(accountNumber, blz)` instead. I guess it it will return the same results; just to be sure that there is no problem with the IBAN checksum function.

Does your bank account number have "99" at position 3-4 (fill with zeros from left if shorter than 10 numbers) e.g. XX99XXXXXX ?

Is it possible for you to modify your bank account number to reproduce the error without providing your bank account number for privacy reasons? Change one or two digits at position 5-9. After that you have to adjust the checksum which is in all variation at tenth position (just try digits 0-9 until it works). Ideally with that modified number iban-rechner will give a valid result and ibantools-germany will return invalid.

**Comment by s-gurevich** [comment]
@baumerdev 

- yes, Bankleitzahl is 30060601
- isValidAccountNumberBLZ(accountNumber, blz) returns false
- no, the IBAN starts with DE97, not "99" at position 3-4

Finding an alternative IBAN might take a while. Maybe this helps already.

Thanks a lot for your help and effort!

**Comment by s-gurevich** [comment]
BTW Account number starts with 3 zeros (seems to be short and filled with zeros, as you stated)

**Comment by s-gurevich** [comment]
Maybe also helpful (comment from the validation page mentioned above):

> 
> Die Prüfziffer in der Kontonummer stimmt. 
> 
> Methode A4, Variante 2, Konto XXX, BLZ 30060601, Prüfziffer X steht an Position 10, erwartete Prüfziffer: X. Überblick über die Berechnung: Nimm die Ziffern auf den Positionen 4 bis 9 - hier: XXX -, multipliziere sie von rechts nach links mit den Gewichten 2,3,4,5,6,7,0,0,0, addiere die Produkte, bilde den Rest der Division durch 7, ziehe das Ergebnis von 7 ab, und das Ergebnis modulo 7 ist die erwartete Prüfziffer.

**Comment by baumerdev** [comment]
Okay "Variante 2", this is helpful since there are 4 possible variations.

If you can confirm that the checksum/the right most digit of your bank account number is "0", then I guess I found the problem.

**Comment by s-gurevich** [comment]
Yes, the checksum is 0.

Great!

**Comment by s-gurevich** [comment]
Thank you very much! :bouquet:

**Comment by baumerdev** [comment]
I just published version 1.2301.4 at npmjs so please install it and let me know if there is still something behaving incorrectly.

**Comment by s-gurevich** [comment]
I can confirm, that 1.2301.4 recognizes the given IBAN as valid now. Thank you very much!
