### ISSUE TITLE
Valid german IBAN is considered invalid

### ISSUE THREAD

**Issue by dennererthal01** [baumerdev/ibantools-germany#23]
## Expected Behavior
A specific valid IBAN is recognized as valid by isValidIBAN function.

## Actual Behavior
A specific valid IBAN is NOT recognized as valid by isValidIBAN function.

## Steps to Reproduce the Problem

1. Import the function from the library: `import { isValidIBAN } from 'ibantools-germany'`
2. Verify the IBAN `<REMOVED>`: `isValidIBAN("<REMOVED>")`
3. The expected result of the function is `true`, but it returns `false`. Testing the IBAN on [this](https://www.iban-rechner.de/iban_validieren.html) website returns that it is valid.

## Specifications

- Version: 1.2402.0
- Platform: Google Chrome Version 127.0.6533.120

**Comment by dennererthal01** [comment]
By the way, thanks a lot for your work! This is the most accurate IBAN validator for german IBANs I have ever saw and would happily donate if you have any form of crowdfunding.

**Comment by baumerdev** [comment]
Thanks for the kind words. Currently I'm not offering funding/sponsorships, but good to know that this piece of software has its worth to some devs.

I published version [1.2402.1](https://www.npmjs.com/package/ibantools-germany/v/1.2402.1) which should fix your issue. If so, let me know so I can close this issue. And if the IBAN above is a real IBAN you may want to redact it due to privacy.

**Comment by dennererthal01** [comment]
It's working as expected now, you may close the issue. Thanks for fixing it so quickly! 

I removed the IBAN as it's a real one, but I had permission from the owner to post it beforehand so all is good.
